name: OpenSSF Scorecard

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # every Sunday

permissions:
  contents: read

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Run Scorecard"
        uses: ossf/scorecard-action@v2.1.1
        with:
          results_file: results.sarif
          results_format: sarif

      - name: "Upload SARIF file"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
          permissions: read-all




