name: OpenSSF Scorecard

on:
  push:
    branches: [main]
  pull_request:
     branches: [main]

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@v3

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
